# Number of days of inactivity before an issue becomes stale
daysUntilStale: 120
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 14
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
  - bug
  - help wanted
# Label to use when marking an issue as stale
staleLabel: stale-issue
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed soon if no further activity occurs. Thank you
  for your contributions. Feel free to comment or otherwise update to keep it alive.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  Closing due to old age. Feel free to re-open or ping maintainers.
